name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install ruff
      - run: ruff .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install mypy
      - run: mypy .
